"""init 

Revision ID: c29f23874b47
Revises: 
Create Date: 2024-05-11 16:10:40.412691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29f23874b47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coctails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(asdecimal=True), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('alcohol_level', sa.Enum('LIGHT', 'STRONG', 'MEDIUM', name='alcohol'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tastes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taste', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taste_coctails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taste_id', sa.Integer(), nullable=False),
    sa.Column('coctail_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coctail_id'], ['coctails.id'], ),
    sa.ForeignKeyConstraint(['taste_id'], ['tastes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taste_coctails')
    op.drop_table('tastes')
    op.drop_table('coctails')
    # ### end Alembic commands ###
