"""add new table

Revision ID: dba8df06610a
Revises: 
Create Date: 2024-05-14 01:04:44.211994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dba8df06610a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taste_cocktails')
    op.drop_table('tastes')
    op.drop_column('cocktails', 'alcohol_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktails', sa.Column('alcohol_level', postgresql.ENUM('LIGHT', 'STRONG', 'MEDIUM', name='alcohol'), autoincrement=False, nullable=True))
    op.create_table('tastes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tastes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('taste', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tastes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('taste_cocktails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taste_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cocktail_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], name='taste_cocktails_cocktail_id_fkey'),
    sa.ForeignKeyConstraint(['taste_id'], ['tastes.id'], name='taste_cocktails_taste_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='taste_cocktails_pkey')
    )
    # ### end Alembic commands ###
