STICKERS = ["CAACAgIAAxkBAAEL6YZmG9AXhlN_-CcmWhL3meLV2gU1nwACwAUAAiMFDQABCeQKn7CDbvA0BA",
            "CAACAgIAAxkBAAEL6YZmG9AXhlN_-CcmWhL3meLV2gU1nwACwAUAAiMFDQABCeQKn7CDbvA0BA",
            "CAACAgIAAxkBAAEL6YpmG9Fo51r3rAYG20rrcwH5rMEPqQACVAUAAiMFDQAB_Wg0xvRPbPY0BA",
            "CAACAgIAAxkBAAEL6ZBmG9JlNV0pYfQr_voDsQWvS9HPOgAC2AUAAiMFDQABmCHlmUm7vp80BA",
            "CAACAgIAAxkBAAEL6YpmG9Fo51r3rAYG20rrcwH5rMEPqQACVAUAAiMFDQAB_Wg0xvRPbPY0BA",
            ]


